### PR TITLE
add think like a computer instructions

### PR DESCRIPTION
**Pull request by Dedekind561**

### CODE REVIEW

**Review by Dedekind561 — COMMENTED** [review]
@gregdyke just lifted this from the Glasgow agenda and popped into here for future use. Once it's in we can start iterating.
I actually think it would be worth recording a group doing this so they get a feel for how it works.

**Review by gregdyke — APPROVED** [review]
I have also just recorded a video for it

**Comment by gregdyke** [comment]
Here is a video where I demo "think like a computer with pen and paper". (First 9mn is the first demo. Then there is some content that trainees can try and the "answer" is the remainder of the video)
https://us02web.zoom.us/rec/share/eDjOynsPI8Qi7xoEGCIRW949a5KVo0lu-YdVjTnmW_asGEgjzpPAxM-a7SwM2jEv.skPG00Pe2LJXkjP2?startTime=1676567201000
Passcode: 0Sa6$a5e

**Comment by Dedekind561** [comment]
That's fantastic - would you be happy to upload this content to YouTube?

**Pull request merged**
